#Importar algumas bibliotecas
import streamlit as st

#*********************************Início da APP***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
#Título:
st.title("Um dia na História")

#Saudação inicial
st.write("Bem vinda, Carolina!")

#Estabelecer o dia:
st.header("1 de novembro")
st.write("O dia 1 de novembro é uma data histórica: foi no 305º dia do calendário gregoriano (306º em anos bissextos) que se deram vários acontecimentos históricos de grande relevo.")

#Caso o utilizador não selecione nenhum tipo de acontecimento esta secção irá encorajá-lo:
st.markdown('De facto, o dia 1 de novembro é um um dia - desculpa pelo pleonasmo - *histórico*. Algumas pessoas **nasceram**, outras **morreram**; deram-se **eventos**... . Se te apetecer, Carolina, estás à vontade para descobrir o que aconteceu ao certo ao longo da história nesta data (para isso, podes utilizar a "*side bar*"). Deixo-te um insentivo: aqui algures, nesta app, existe uma ***secção escondida***!')

#Estabelecer a categoria de acontecimentos
with st.sidebar:
    st.markdown("**Tipos de acontecimentos a visualizar:**")
    EventosHistóricos = st.toggle("Eventos Históricos")
    Nascimentos = st.toggle("Nascimentos")
    Mortes = st.toggle("Mortes")
    condition = True #Uma variável que permite interromper o código, para que não exista repetição de dados apresentados.

#Eliminar possíveis erros:
if (EventosHistóricos and Nascimentos) or (EventosHistóricos and Mortes) or (Nascimentos and Mortes):
    col1, col2, col3 = st.columns(3)
    col1.metric("" , "" , "")
    col2.metric("" , "Erro*" , "")
    col3.metric("" , "" , "")
    st.write("*Esta APP foi desenvolvida de forma a evidenciar apenas uma categoria de acontecimentos em simultaneo.")

#Eventos históricos:
elif EventosHistóricos:
        st.subheader("Principais Eventos Históricos" , divider= "rainbow")
        #Estabelecer que épocas evidenciar
        with st.sidebar:
            st.markdown("**Por favor selecione as principais épocas a visualizar:**")
            SeculoIaXI = st.toggle("Século I a século XI")                                  #I a XI
            SeculoXIIaXIX = st.toggle("Século XII a seculo XIX")                            #XII a XIX
            SeculoXX = st.toggle("Século XX")                                               #XX
            SeculoXXI = st.toggle("Século XXI")                                             #XXI
            TodasAsEpocas = st.toggle("Todas as épocas")                                    #Todas
        if TodasAsEpocas:
            condition = False
            st.markdown("")
            st.subheader("365:")
            st.markdown("Os ***Alamanos*** cruzam o rio Reno e invadem a *Gália*. O **Imperador romano Valentiniano** muda-se para *Paris* para comandar o exército e defender as cidades gaulesas.")
            st.image("reno.jpg" , caption="Travessia do Reno")
            st.subheader("996:")
            st.markdown("O ***Imperador Otão III*** emite uma escritura para **Gottschalk**, *Bispo de Freising*, que é o documento mais antigo conhecido onde se emprega o uso do nome ***Ostarrîchi*** (Áustria no alemão antigo erudito).")
            st.image("austria.png" , caption="Bandeira Austríaca")
            st.subheader("1009:")
            st.markdown("As forças *berberes*, lideradas por **Solimão Almostaim** derrotam o ***califa omíada Maomé II***  na batalha de **Alcolea**.")
            st.image("alcolea.jpg" , caption="Batalha de Alcolea")
            st.subheader("1141:")
            st.markdown('O reinado da ***Imperatriz Matilde*** como *"Senhora dos Ingleses"* termina com ***Estêvão de Blois*** a recuperar o título de **Rei da Inglaterra**.')
            st.image("matilde.jpg" , caption="Imperatriz Matilde")
            st.subheader("1179:")
            st.markdown("***Filipe II*** é coroado como **Rei da França**.")
            st.image("filipe.png" , caption="Filipe II")
            st.subheader("1214:")
            st.markdown("A cidade portuária de ***Sinope*** se rende aos **turcos seljúcidas**.")
            st.image("sinope.JPG" , caption="Aspeto atual de Sinope")
            st.subheader("1301:")
            st.markdown("***Carlos de Valois*** entra em *Florença* com os **guelfos negros** e devasta a cidade.")
            st.image("carlos.jpg" , caption="Carlos de Valois")
            st.subheader("1386:")
            st.markdown("É assinado o ***Tratado de Monção***.")
            st.image("monção.jpg" , caption="Tratado de Monção")
            st.subheader("1501:")
            st.markdown("Descobrimento da ***Baía de Todos-os-Santos***, no *litoral brasileiro*.")
            st.image("baia.jpg" , caption="Baía de Todos-os-Santos")
            st.subheader("1503:")
            st.markdown("É eleito o ***Papa Júlio II***.")
            st.image("papa.jpg" , caption="Papa Júlio II")
            st.subheader("1512:")
            st.markdown("O **teto da Capela Sistina**, pintado por ***Miguel Ângelo***, é exibido ao público pela primeira vez.")
            st.image("sistina.jpg" , caption="O teto da Capela Sistina")
            st.subheader("1520:")
            st.markdown("O ***Estreito de Magalhães***, a passagem imediatamente ao sul da América do Sul continental que liga os oceanos *Pacífico* e *Atlântico*, é descoberto e navegado pela primeira vez pelo explorador português **Fernão de Magalhães** durante a primeira viagem de *circum-navegação* registrada.")
            st.image("estreito.jpg" , caption="Imagem satélite do Estreito de Magalhães")
            st.subheader("1555:")
            st.markdown("**Huguenotes franceses** estabelecem a colônia da ***França Antártica*** no atual *Rio de Janeiro*, Brasil.")
            st.image("rio.jpg" , caption="Rio de Janeiro")
            st.subheader("1570:")
            st.markdown("O **Dilúvio de Todos os Santos** devasta a *costa holandesa*.")
            st.image("costa.jpg" , caption="Pintura representativa da costa holandesa")
            st.subheader("1604:")
            st.markdown("A *tragédia* ***Otelo***, de **William Shakespeare**, é apresentada pela primeira vez, no *Palácio de Whitehall*, em **Londres**.")
            st.image("otelo.jpg" , caption='Imagem de uma encenação de "Otelo"')
            st.subheader("1611:")
            st.markdown("A peça de **Shakespeare** ***A Tempestade*** é apresentada pela primeira vez, no *Palácio de Whitehall*, em **Londres**.")
            st.image("tempestade.jpg" , caption="Edição literária da peça")
            st.subheader("1612:")
            st.markdown("Durante o ***Tempo de Dificuldades***, as **tropas polonesas** são *expulsas* do **Kitai-gorod de Moscou** por **tropas russas** sob o comando de ***Dmitri Pojarski***.")
            st.image("dmitry.jpg" , caption="Dmitry Pojarski")
            st.subheader("1755:")
            st.markdown("O ***Terramoto de Lisboa***, que destrói grande parte de *Lisboa*, mata entre **60** e 90 mil** pessoas.")
            st.image("terramoto.jpeg" , caption="O Terramoto de Lisboa")
            st.markdown("O ***Tsunâmi do Brasil***, destroi de forma parcial a *costa nordeste*.")
            st.image("tsunami.jpg" , caption="Representação dos efeitos do tsunami.")
            st.subheader("1765:")
            st.markdown("O **Parlamento britânico** promulga a *Lei do selo sobre as Treze Colônias*, a fim de ajudar a pagar pelas operações militares britânicas na *América do Norte*.")
            st.image("reino_unido.png" , caption="Bandeira do Reino Unido")
            st.subheader("1790:")
            st.markdown("***Edmund Burke*** publica **Reflexões sobre a Revolução na França**, na qual prevê que a **Revolução Francesa** terminará em *desastre*.")
            st.image("burke.jpg" , caption="Edmund Burke")
            st.subheader("1800:")
            st.markdown("***John Adams*** torna-se o primeiro **presidente dos Estados Unidos** a viver na *Mansão Executiva* (mais tarde renomeada **Casa Branca**).")
            st.image("casa_branca.jpg" , caption="A Casa Branca")
            st.subheader("1805:")
            st.markdown("**Napoleão Bonaparte*** invade a **Áustria** durante a *Guerra da Terceira Coalizão*.")
            st.image("napoleao.jpg" , caption="Napoleão Bonaparte")
            st.subheader("1814:")
            st.markdown("O ***Congresso de Viena*** começa com o intúito redesenhar o *mapa político europeu* após a derrota da **França** nas ***Guerras Napoleônicas***.")
            st.image("congresso.jpg" , caption="Congresso de Viena")
            st.subheader("1861:")
            st.markdown("Durante a ***Guerra Civil Americana***, o *presidente dos Estados Unidos*, **Abraham Lincoln**, nomeia **George B. McClellan** como comandante do *Exército da União*, substituindo o general **Winfield Scott**.")
            st.image("lincoln.jpg" , caption="Abraham Lincoln")
            st.subheader("1894:")
            st.markdown("***Nicolau II*** torna-se o novo (e último) **czar da Rússia** após a morte do seu pai, ***Alexandre III***.")
            st.image("nicolau.jpg" , caption="Nicolau II")
            st.subheader("1897:")
            st.markdown("O primeiro edifício da ***Biblioteca do Congresso*** abre suas portas ao público; a biblioteca já havia sido alojada na **Sala de Leitura do Congresso** no *Capitólio dos Estados Unidos*.")
            st.image("biblioteca.jpeg" , caption="A Biblioteca do Congresso")
            st.subheader("1911:")
            st.markdown("A primeira **missão de bombardeio aéreo** de combate do mundo ocorre na *Líbia* durante a ***Guerra Ítalo-Turca***. O segundo-tenente ***Giulio Gavotti***, da *Itália*, solta várias pequenas bombas.")
            st.image("bombardeiro.jpg" , caption="O Bombardeiro utilizado na missão")
            st.subheader("1914:")
            st.markdown("Durante a ***Primeira Guerra Mundial***, a ***Batalha de Coronel***, a primeira *derrota* da **Marinha Real Britanica** na guerra com a *Alemanha*, é travada na *costa oeste do Chile*, no **Pacífico**, com a perda do **HMS Good Hope** e do **HMS Monmouth**.")
            st.image("coronel.jpg" , caption="Batalha de Coronel")
            st.subheader("1918:")
            st.markdown("A ***Ucrania Ocidental*** separa-se da **Áustria-Hungria**.")
            st.image("ucrania_ocidental.png" , caption="Mapa da Ucrânia Ocidental")
            st.subheader("1919:")
            st.markdown("O ***Caminho de Ferro Araraquara*** é encampada pelo *Estado de São Paulo*.")
            st.image("araraquara.jpg" , caption="O Caminho de Ferro")
            st.subheader("1922:")
            st.markdown("Extinção do ***Império Otomano*** com a *abolição* do cargo de *sultão* pela **Grande Assembleia Nacional** (parlamento turco); a ***República da Turquia*** seria oficialmente proclamada em 29 de outubro de 1923.")
            st.image("otomano.jpg" , caption="Mapa do Império Otomano")
            st.subheader("1928:")
            st.markdown("A ***Lei de Adoção e Implementação*** do alfabeto *turco* substitui o alfabeto *árabe* pelo **alfabeto latino**.")
            st.image("alfabeto.png" , caption="O Alfabeto Latino")
            st.subheader("1942:")
            st.markdown("Entra em vigor o **padrão monetário** do ***Cruzeiro*** no *Brasil*.")
            st.image("cruzeiro.jpg" , caption="Uma moeda do padrão monetário do Cruzeiro")
            st.subheader("1944:")
            st.markdown("Durante a ***Segunda Guerra Mundial***, um **F-13 Superfortress** da *Forças Aéreas do Exército dos Estados Unidos* efetua o primeiro voo de uma aeronave *aliada* sobre a região de *Tóquio*, no *Japão*, desde o *Ataque Doolittle* de **1942**.")
            st.image("f13.jpg" , caption="F-13 Superfortress")
            st.subheader("1945:")
            st.markdown("A ***Comunidade da Austrália*** é *admitida* como **Estado-Membro** da ***ONU***.")
            st.image("onu.jpg" , caption="A sala da Assembleia Geral das Nações Unidas, em Nova York")
            st.subheader("1950:")
            st.markdown("O ***Papa Pio XII*** afirma a **infalibilidade papal** quando define solenemente o *dogma* da ***Assunção de Maria***.")
            st.image("pio.jpg" , caption="Papa Pio XII")
            st.markdown("Os **nacionalistas porto-riquenhos** ***Griselio Torresola*** e ***Oscar Collazo*** tentam *assassinar* o *presidente dos Estados Unidos*, ***Harry S. Truman***.")
            st.image("truman.jpg" , caption="Harry Truman")
            st.subheader("1951:")
            st.markdown('Durante a ***Operação Buster-Jangle***, *Seis mil e quinhentos* soldados do *Exército dos Estados Unidos* são expostos a **explosões atómicas** de ***"Desert Rock"*** para fins de treinamento, no Nevada. A participação **não** é ***voluntária***.')
            st.image("buster.jpg" , caption="Imagem de uma explosão durante a operação")
            st.subheader("1952:")
            st.markdown("Durante um **teste de armas nucleares**, os *Estados Unidos* detonam com sucesso ***Ivy Mike***, o primeiro dispositivo *termonuclear*, no atol de *Enewetak*. A explosão teve um rendimento de **dez megatoneladas de TNT**.")
            st.image("ivy.jpg" , caption='A nuvem "cogumelo" formada após o detonamento da Ivy Mike')
            st.subheader("1954:")
            st.markdown("A ***Frente de Libertação Nacional*** dispara os primeiros tiros da **Guerra de Independência Argelina**.")
            st.image("libertação.png" , caption="Emblema da Frente de Libertação Nacional")
            st.subheader("1955:")
            st.markdown("Inicio da ***Guerra do Vietname***.")
            st.image("vietnam.jpg")
            st.subheader("1956:")
            st.markdown("Durante a ***Revolução Húngara***, Imre Nagy anuncia a neutralidade e a retirada da Hungria do Pacto de Varsóvia. As tropas soviéticas começam a entrar novamente na Hungria, contrariamente às garantias do governo soviético.")
            st.image("varsovia.jpg" , caption="Emblema do pacto de Varsóvia")
            st.subheader("1957:")
            st.markdown("A ***Ponte de Mackinac***, a maior ponte *suspensa* do mundo entre ancoradouros da época, abre-se ao tráfego que liga as penínsulas superior e inferior do **Michigan**.")
            st.image("ponte.jpg")
            st.subheader("1960:")
            st.markdown("O tratado da primeira organização de integração económica da **Europa**, a ***Benelux***, entra em vigor.")
            st.image("benelux.png" , caption="Mapa da área abrangida pelo tratado")
            st.subheader("1963:")
            st.markdown("O ***Observatório de Arcibo***, *Porto Rico*, é oficialmente inaugurado, com o *maior* ***radiotelecópio*** já construído.")
            st.image("arecibo.jpg")
            st.markdown("Começa um ***Golpe de Estado*** no *Vietname do Sul*.")
            st.image("golpe.jpg")
            st.subheader("1965:")
            st.markdown("Durante o ***Golpe Militar de 1964***, no *Brasil*, são instituídos os ***Atos Complementares 2 e 3***. O **primeiro** trata de **disposições transitórias até o estabelecimento de tribunais federais** em primeira instância e o *segundo* determinava as formalidades para a **aplicação da suspensão de direitos políticos e garantias constitucionais**.")
            st.image("brasil.jpg" , caption="Imagem alusiva ao Golpe Militar de 1964")
            st.subheader("1973:")
            st.markdown("O **estado indiano de Maiçor** é renomeado como ***Carnataca*** para representar todas as regiões de *Karunadu*.")
            st.image("carnataca.jpg" , caption="Mapa do Estado Indiano de Carnataca")
            st.subheader("1979:")
            st.markdown("Na *Bolívia*, o coronel ***Alberto Natusch Busch*** realiza um **Golpe de Estado** contra o ***governo constitucional*** de ***Wálter Guevara Arze***.")
            st.image("alberto.jpg" , caption="O Coronel Alberto Natusch Busch")
            st.subheader("1980:")
            st.markdown("Início do ***Sistema Brasileiro de Televisão***.")
            st.image("sbt.jpg")
            st.subheader("1981:")
            st.markdown("***Antígua e Barbuda*** obtém a **independência** do ***Reino Unido***.")
            st.image("barbuda.jpeg" , caption="A bandeira de Antigua e Barbuda")
            st.subheader("1984:")
            st.markdown("Após o *assassinato* de ***Indira Gandhi***, **primeira-ministra da Índia**, em 31 de outubro de 1984, por dois de seus **guarda-costas** *siques*, eclodem motins *anti-siques*.")
            st.image("indira.jpg" ,  caption="Indira Gandhi")
            st.subheader("1991:")
            st.markdown("O *presidente da República Chechena*, ***Dzhokhar Dudayev***, declara a *soberania* da ***República Chechena da Ichkeria*** da **Federação Russa**.")
            st.image("chechenia.jpg" , caption="Bandeira Chechena")
            st.subheader("1993:")
            st.markdown("Entra em vigor o ***Tratado de Maastricht***, que institui formalmente a ***União Europeia***.")
            st.image("ue.png")
            st.subheader("1994:")
            st.markdown("Ocorre o **MTV Unplugged** da banda ***Nirvana***.")
            st.image("nirvana.jpg" , caption="Kurt Cobain, vocalista dos Nirvana")
            st.subheader("1995:")
            st.markdown("O ***Congresso Nacional Africano*** vence as *eleições multirraciais* na **África do Sul**.")
            st.image("africaS.png" , caption="Bandeira Sul Africana")
            st.subheader("2000:")
            st.markdown("A ***União Estatal de Sérvia e Montenegro*** (atual *República da Sérvia*) é admitida como **Estado-Membro** da ***ONU***.")
            st.image("servia.png" , caption="Bandeira da Sérvia")
            st.subheader("2001:")
            st.markdown("***Turquia***, ***Austrália*** e ***Canadá*** concordam em empenhar **tropas** na *invasão do Afeganistão*.")
            st.image("afeganistao.jpg")
            st.subheader("2002:")
            st.markdown("A estudante ***Suzane von Richthofen***, o seu *namorado*, ***Daniel Cravinhos***, e o *irmão dele*, ***Cristian Cravinhos***, **matam** os ***pais da jovem***, ***Manfred Albert Freiherr von Richthofen*** e ***Marísia von Richthofen***, em *São Paulo*.")
            st.image("manfred_e_Marísia.jpg" , caption="Os pais da jovem")
            st.subheader("2022:")
            st.markdown("A ***tempestade tropical Nalgae*** causa *inundações*, *deslizamentos de terra* e, pelo menos, **150 mortos** nas *Filipinas*.")
            st.image("filipinas.png" , caption="Bandeira das Filipinas")
            st.subheader("2023:")
            st.markdown("O ***Texas Rangers*** consegue a primeira **Série Mundial das Grandes Ligas** da sua história derrotando o ***Arizona Diamondbacks*** no quinto jogo de uma série à melhor de 7.")
            st.image("rangers.jpeg")
        if SeculoIaXI and condition == True:
            st.subheader("365:")
            st.markdown("Os ***Alamanos*** cruzam o rio Reno e invadem a *Gália*. O **Imperador romano Valentiniano** muda-se para *Paris* para comandar o exército e defender as cidades gaulesas.")
            st.image("reno.jpg" , caption="Travessia do Reno")
            st.subheader("996:")
            st.markdown("O ***Imperador Otão III*** emite uma escritura para **Gottschalk**, *Bispo de Freising*, que é o documento mais antigo conhecido onde se emprega o uso do nome ***Ostarrîchi*** (Áustria no alemão antigo erudito).")
            st.image("austria.png" , caption="Bandeira Austríaca")
        if SeculoXIIaXIX and condition == True:
            st.subheader("1009:")
            st.markdown("As forças *berberes*, lideradas por **Solimão Almostaim** derrotam o ***califa omíada Maomé II***  na batalha de **Alcolea**.")
            st.image("alcolea.jpg" , caption="Batalha de Alcolea")
            st.subheader("1141:")
            st.markdown('O reinado da ***Imperatriz Matilde*** como *"Senhora dos Ingleses"* termina com ***Estêvão de Blois*** a recuperar o título de **Rei da Inglaterra**.')
            st.image("matilde.jpg" , caption="Imperatriz Matilde")
            st.subheader("1179:")
            st.markdown("***Filipe II*** é coroado como **Rei da França**.")
            st.image("filipe.png" , caption="Filipe II")
            st.subheader("1214:")
            st.markdown("A cidade portuária de ***Sinope*** se rende aos **turcos seljúcidas**.")
            st.image("sinope.JPG" , caption="Aspeto atual de Sinope")
            st.subheader("1301:")
            st.markdown("***Carlos de Valois*** entra em *Florença* com os **guelfos negros** e devasta a cidade.")
            st.image("carlos.jpg" , caption="Carlos de Valois")
            st.subheader("1386:")
            st.markdown("É assinado o ***Tratado de Monção***.")
            st.image("monção.jpg" , caption="Tratado de Monção")
            st.subheader("1501:")
            st.markdown("Descobrimento da ***Baía de Todos-os-Santos***, no *litoral brasileiro*.")
            st.image("baia.jpg" , caption="Baía de Todos-os-Santos")
            st.subheader("1503:")
            st.markdown("É eleito o ***Papa Júlio II***.")
            st.image("papa.jpg" , caption="Papa Júlio II")
            st.subheader("1512:")
            st.markdown("O **teto da Capela Sistina**, pintado por ***Miguel Ângelo***, é exibido ao público pela primeira vez.")
            st.image("sistina.jpg" , caption="O teto da Capela Sistina")
            st.subheader("1520:")
            st.markdown("O ***Estreito de Magalhães***, a passagem imediatamente ao sul da América do Sul continental que liga os oceanos *Pacífico* e *Atlântico*, é descoberto e navegado pela primeira vez pelo explorador português **Fernão de Magalhães** durante a primeira viagem de *circum-navegação* registrada.")
            st.image("estreito.jpg" , caption="Imagem satélite do Estreito de Magalhães")
            st.subheader("1555:")
            st.markdown("**Huguenotes franceses** estabelecem a colônia da ***França Antártica*** no atual *Rio de Janeiro*, Brasil.")
            st.image("rio.jpg" , caption="Rio de Janeiro")
            st.subheader("1570:")
            st.markdown("O **Dilúvio de Todos os Santos** devasta a *costa holandesa*.")
            st.image("costa.jpg" , caption="Pintura representativa da costa holandesa")
            st.subheader("1604:")
            st.markdown("A *tragédia* ***Otelo***, de **William Shakespeare**, é apresentada pela primeira vez, no *Palácio de Whitehall*, em **Londres**.")
            st.image("otelo.jpg" , caption='Imagem de uma encenação de "Otelo"')
            st.subheader("1611:")
            st.markdown("A peça de **Shakespeare** ***A Tempestade*** é apresentada pela primeira vez, no *Palácio de Whitehall*, em **Londres**.")
            st.image("tempestade.jpg" , caption="Edição literária da peça")
            st.subheader("1612:")
            st.markdown("Durante o ***Tempo de Dificuldades***, as **tropas polonesas** são *expulsas* do **Kitai-gorod de Moscou** por **tropas russas** sob o comando de ***Dmitri Pojarski***.")
            st.image("dmitry.jpg" , caption="Dmitry Pojarski")
            st.subheader("1755:")
            st.markdown("O ***Terramoto de Lisboa***, que destrói grande parte de *Lisboa*, mata entre **60** e 90 mil** pessoas.")
            st.image("terramoto.jpeg" , caption="O Terramoto de Lisboa")
            st.markdown("O ***Tsunâmi do Brasil***, destroi de forma parcial a *costa nordeste*.")
            st.image("tsunami.jpg" , caption="Representação dos efeitos do tsunami.")
            st.subheader("1765:")
            st.markdown("O **Parlamento britânico** promulga a *Lei do selo sobre as Treze Colônias*, a fim de ajudar a pagar pelas operações militares britânicas na *América do Norte*.")
            st.image("reino_unido.png" , caption="Bandeira do Reino Unido")
            st.subheader("1790:")
            st.markdown("***Edmund Burke*** publica **Reflexões sobre a Revolução na França**, na qual prevê que a **Revolução Francesa** terminará em *desastre*.")
            st.image("burke.jpg" , caption="Edmund Burke")
            st.subheader("1800:")
            st.markdown("***John Adams*** torna-se o primeiro **presidente dos Estados Unidos** a viver na *Mansão Executiva* (mais tarde renomeada **Casa Branca**).")
            st.image("casa_branca.jpg" , caption="A Casa Branca")
            st.subheader("1805:")
            st.markdown("**Napoleão Bonaparte*** invade a **Áustria** durante a *Guerra da Terceira Coalizão*.")
            st.image("napoleao.jpg" , caption="Napoleão Bonaparte")
            st.subheader("1814:")
            st.markdown("O ***Congresso de Viena*** começa com o intúito redesenhar o *mapa político europeu* após a derrota da **França** nas ***Guerras Napoleônicas***.")
            st.image("congresso.jpg" , caption="Congresso de Viena")
            st.subheader("1861:")
            st.markdown("Durante a ***Guerra Civil Americana***, o *presidente dos Estados Unidos*, **Abraham Lincoln**, nomeia **George B. McClellan** como comandante do *Exército da União*, substituindo o general **Winfield Scott**.")
            st.image("lincoln.jpg" , caption="Abraham Lincoln")
            st.subheader("1894:")
            st.markdown("***Nicolau II*** torna-se o novo (e último) **czar da Rússia** após a morte do seu pai, ***Alexandre III***.")
            st.image("nicolau.jpg" , caption="Nicolau II")
            st.subheader("1897:")
            st.markdown("O primeiro edifício da ***Biblioteca do Congresso*** abre suas portas ao público; a biblioteca já havia sido alojada na **Sala de Leitura do Congresso** no *Capitólio dos Estados Unidos*.")
            st.image("biblioteca.jpeg" , caption="A Biblioteca do Congresso")
        if SeculoXX and condition == True:
            st.subheader("1911:")
            st.markdown("A primeira **missão de bombardeio aéreo** de combate do mundo ocorre na *Líbia* durante a ***Guerra Ítalo-Turca***. O segundo-tenente ***Giulio Gavotti***, da *Itália*, solta várias pequenas bombas.")
            st.image("bombardeiro.jpg" , caption="O Bombardeiro utilizado na missão")
            st.subheader("1914:")
            st.markdown("Durante a ***Primeira Guerra Mundial***, a ***Batalha de Coronel***, a primeira *derrota* da **Marinha Real Britanica** na guerra com a *Alemanha*, é travada na *costa oeste do Chile*, no **Pacífico**, com a perda do **HMS Good Hope** e do **HMS Monmouth**.")
            st.image("coronel.jpg" , caption="Batalha de Coronel")
            st.subheader("1918:")
            st.markdown("A ***Ucrânia Ocidental*** separa-se da **Áustria-Hungria**.")
            st.image("ucrania_ocidental" , caption="Mapa da Ucrânia Ocidental")
            st.subheader("1919:")
            st.markdown("O ***Caminho de Ferro Araraquara*** é encampada pelo *Estado de São Paulo*.")
            st.image("araraquara.jpg" , caption="O Caminho de Ferro")
            st.subheader("1922:")
            st.markdown("Extinção do ***Império Otomano*** com a *abolição* do cargo de *sultão* pela **Grande Assembleia Nacional** (parlamento turco); a ***República da Turquia*** seria oficialmente proclamada em 29 de outubro de 1923.")
            st.image("otomano.jpg" , caption="Mapa do Império Otomano")
            st.subheader("1928:")
            st.markdown("A ***Lei de Adoção e Implementação*** do alfabeto *turco* substitui o alfabeto *árabe* pelo **alfabeto latino**.")
            st.image("alfabeto.png" , caption="O Alfabeto Latino")
            st.subheader("1942:")
            st.markdown("Entra em vigor o **padrão monetário** do ***Cruzeiro*** no *Brasil*.")
            st.image("cruzeiro.jpg" , caption="Uma moeda do padrão monetário do Cruzeiro")
            st.subheader("1944:")
            st.markdown("Durante a ***Segunda Guerra Mundial***, um **F-13 Superfortress** da *Forças Aéreas do Exército dos Estados Unidos* efetua o primeiro voo de uma aeronave *aliada* sobre a região de *Tóquio*, no *Japão*, desde o *Ataque Doolittle* de **1942**.")
            st.image("f13.jpg" , caption="F-13 Superfortress")
            st.subheader("1945:")
            st.markdown("A ***Comunidade da Austrália*** é *admitida* como **Estado-Membro** da ***ONU***.")
            st.image("onu.jpg" , caption="A sala da Assembleia Geral das Nações Unidas, em Nova York")
            st.subheader("1950:")
            st.markdown("O ***Papa Pio XII*** afirma a **infalibilidade papal** quando define solenemente o *dogma* da ***Assunção de Maria***.")
            st.image("pio.jpg" , caption="Papa Pio XII")
            st.markdown("Os **nacionalistas porto-riquenhos** ***Griselio Torresola*** e ***Oscar Collazo*** tentam *assassinar* o *presidente dos Estados Unidos*, ***Harry S. Truman***.")
            st.image("truman.jpg" , caption="Harry Truman")
            st.subheader("1951:")
            st.markdown('Durante a ***Operação Buster-Jangle***, *Seis mil e quinhentos* soldados do *Exército dos Estados Unidos* são expostos a **explosões atómicas** de ***"Desert Rock"*** para fins de treinamento, no Nevada. A participação **não** é ***voluntária***.')
            st.image("buster.jpg" , caption="Imagem de uma explosão durante a operação")
            st.subheader("1952:")
            st.markdown("Durante um **teste de armas nucleares**, os *Estados Unidos* detonam com sucesso ***Ivy Mike***, o primeiro dispositivo *termonuclear*, no atol de *Enewetak*. A explosão teve um rendimento de **dez megatoneladas de TNT**.")
            st.image("ivy.jpg" , caption='A nuvem "cogumelo" formada após o detonamento da Ivy Mike')
            st.subheader("1954:")
            st.markdown("A ***Frente de Libertação Nacional*** dispara os primeiros tiros da **Guerra de Independência Argelina**.")
            st.image("libertação.png" , caption="Emblema da Frente de Libertação Nacional")
            st.subheader("1955:")
            st.markdown("Inicio da ***Guerra do Vietname***.")
            st.image("vietnam.jpg")
            st.subheader("1956:")
            st.markdown("Durante a ***Revolução Húngara***, Imre Nagy anuncia a neutralidade e a retirada da Hungria do Pacto de Varsóvia. As tropas soviéticas começam a entrar novamente na Hungria, contrariamente às garantias do governo soviético.")
            st.image("varsovia.jpg" , caption="Emblema do pacto de Varsóvia")
            st.subheader("1957:")
            st.markdown("A ***Ponte de Mackinac***, a maior ponte *suspensa* do mundo entre ancoradouros da época, abre-se ao tráfego que liga as penínsulas superior e inferior do **Michigan**.")
            st.image("ponte.jpg")
            st.subheader("1960:")
            st.markdown("O tratado da primeira organização de integração económica da **Europa**, a ***Benelux***, entra em vigor.")
            st.image("benelux.png" , caption="Mapa da área abrangida pelo tratado")
            st.subheader("1963:")
            st.markdown("O ***Observatório de Arcibo***, *Porto Rico*, é oficialmente inaugurado, com o *maior* ***radiotelecópio*** já construído.")
            st.image("arecibo.jpg")
            st.markdown("Começa um ***Golpe de Estado*** no *Vietname do Sul*.")
            st.image("golpe.jpg")
            st.subheader("1965:")
            st.markdown("Durante o ***Golpe Militar de 1964***, no *Brasil*, são instituídos os ***Atos Complementares 2 e 3***. O **primeiro** trata de **disposições transitórias até o estabelecimento de tribunais federais** em primeira instância e o *segundo* determinava as formalidades para a **aplicação da suspensão de direitos políticos e garantias constitucionais**.")
            st.image("brasil.jpg" , caption="Imagem alusiva ao Golpe Militar de 1964")
            st.subheader("1973:")
            st.markdown("O **estado indiano de Maiçor** é renomeado como ***Carnataca*** para representar todas as regiões de *Karunadu*.")
            st.image("carnataca.jpg" , caption="Mapa do Estado Indiano de Carnataca")
            st.subheader("1979:")
            st.markdown("Na *Bolívia*, o coronel ***Alberto Natusch Busch*** realiza um **Golpe de Estado** contra o ***governo constitucional*** de ***Wálter Guevara Arze***.")
            st.image("alberto.jpg" , caption="O Coronel Alberto Natusch Busch")
            st.subheader("1980:")
            st.markdown("Início do ***Sistema Brasileiro de Televisão***.")
            st.image("sbt.jpg")
            st.subheader("1981:")
            st.markdown("***Antígua e Barbuda*** obtém a **independência** do ***Reino Unido***.")
            st.image("barbuda.jpeg" , caption="A bandeira de Antigua e Barbuda")
            st.subheader("1984:")
            st.markdown("Após o *assassinato* de ***Indira Gandhi***, **primeira-ministra da Índia**, em 31 de outubro de 1984, por dois de seus **guarda-costas** *siques*, eclodem motins *anti-siques*.")
            st.image("indira.jpg" ,  caption="Indira Gandhi")
            st.subheader("1991:")
            st.markdown("O *presidente da República Chechena*, ***Dzhokhar Dudayev***, declara a *soberania* da ***República Chechena da Ichkeria*** da **Federação Russa**.")
            st.image("chechenia.jpg" , caption="Bandeira Chechena")
            st.subheader("1993:")
            st.markdown("Entra em vigor o ***Tratado de Maastricht***, que institui formalmente a ***União Europeia***.")
            st.image("ue.png")
            st.subheader("1994:")
            st.markdown("Ocorre o **MTV Unplugged** da banda ***Nirvana***.")
            st.image("nirvana.jpg" , caption="Kurt Cobain, vocalista dos Nirvana")
            st.subheader("1995:")
            st.markdown("O ***Congresso Nacional Africano*** vence as *eleições multirraciais* na **África do Sul**.")
            st.image("africaS.png" , caption="Bandeira Sul Africana")
            st.subheader("2000:")
            st.markdown("A ***União Estatal de Sérvia e Montenegro*** (atual *República da Sérvia*) é admitida como **Estado-Membro** da ***ONU***.")
            st.image("servia.png" , caption="Bandeira da Sérvia")
        if SeculoXXI and condition == True:
            st.subheader("2001:")
            st.markdown("***Turquia***, ***Austrália*** e ***Canadá*** concordam em empenhar **tropas** na *invasão do Afeganistão*.")
            st.image("afeganistao.jpg")
            st.subheader("2002:")
            st.markdown("A estudante ***Suzane von Richthofen***, o seu *namorado*, ***Daniel Cravinhos***, e o *irmão dele*, ***Cristian Cravinhos***, **matam** os ***pais da jovem***, ***Manfred Albert Freiherr von Richthofen*** e ***Marísia von Richthofen***, em *São Paulo*.")
            st.image("manfred_e_Marísia.jpg" , caption="Os pais da jovem")
            st.subheader("2022:")
            st.markdown("A ***tempestade tropical Nalgae*** causa *inundações*, *deslizamentos de terra* e, pelo menos, **150 mortos** nas *Filipinas*.")
            st.image("filipinas.png" , caption="Bandeira das Filipinas")
            st.subheader("2023:")
            st.markdown("O ***Texas Rangers*** consegue a primeira **Série Mundial das Grandes Ligas** da sua história derrotando o ***Arizona Diamondbacks*** no quinto jogo de uma série à melhor de 7.")
            st.image("rangers.jpeg") 

#Nascimentos:
elif Nascimentos:
        st.subheader("Pricipais Nascimentos" , divider= "rainbow")
        #Estabelecer épocas a evidenciar
        with st.sidebar:
            st.markdown("**Por favor selecione as principais épocas a visualizar:**")
            AteSeculoXIX = st.toggle("Anteriores ao século XIX")
            SeculoXIX = st.toggle("Século XIX")
            SeculoXX = st.toggle("Século XX")
            if SeculoXX:
                PrimeiraMetade = st.checkbox("1901-1950")
                SegundaMetade = st.checkbox("1951-2000")
            SeculoXXI = st.toggle("Século XXI")
            TodasAsEpocas = st.toggle("Todas as épocas")
        if TodasAsEpocas:
            condition = False
            st.subheader("846:")
            st.markdown("Nasce ***Luís II de França***. (m. 879)")
            st.image("luis.jpg")
            st.subheader("1339:")
            st.markdown("Nasce ***Rodolfo IV da Áustria***. (m. 1365)")
            st.image("rodolfo.jpg")
            st.subheader("1526:")
            st.markdown("Nasce ***Catarina Jagelão***, Rainha da *Suécia*. (m. 1583)")
            st.image("jagelão.jpg")
            st.subheader("1530:")
            st.markdown("Nasce ***Étienne de La Boétie***, filósofo e humanista *francês*. (m. 1563)")
            st.image("etienne.jpg")
            st.subheader("1549:")
            st.markdown("Nasce ***Ana de Áustria***, Rainha de *Espanha*. (m. 1580)")
            st.image("ana.jpg")
            st.subheader("1593:")
            st.markdown("Nasce ***Abel Servien***, diplomata *francês*. (m.1659)")
            st.image("abel.jpg")
            st.subheader("1596:")
            st.markdown("Nasce ***Pietro de Cortona***, pintor e arquiteto *toscano*. (m.1669)")
            st.image("pietro.jpeg")
            st.subheader("1636:")
            st.markdown("Nasce ***Nicolas Boileau***, crítico literário e poeta *francês*. (m.1711)")
            st.image("nicolas.jpg")
            st.subheader("1661:")
            st.markdown("Nasce ***Luís, Grande Delfim de França***. (m. 1661)")
            st.image("delfim.jpg")
            st.subheader("1713:")
            st.markdown("Nasce ***Antonio Genovesi***, escritor e filósofo *napolitano*. (m. 1769)")
            st.image("antonio.jpg")
            st.subheader("1717:")
            st.markdown("Nasce ***Ana Teresa de Saboia***, nobre *francesa*. (m.1745)")
            st.image("saboia.jpg")
            st.subheader("1743:")
            st.markdown("Nasce ***Johann Friedrich Wilhelm Herbst***, naturalista e entomologista *alemão*. (m. 1807)")
            st.image("johann.jpg")
            st.subheader("1757:")
            st.markdown("Nasce ***Antonio Canova***, escultor *veneziano*. (m.1822)")
            st.image("canova.jpg")
            st.subheader("1762:")
            st.markdown("Nasce ***Antônio de Santa Úrsula Rodovalho***, religioso franciscano nascido no *Brasil Colonial*. (m. 1817)")
            st.image("franciscanos.jpg" , caption="Grupo de religiosos a envergarem o típico traje franciscano")
            st.markdown("Nasce ***Spencer Perceval***, político *britânico*. (m. 1812)")
            st.image("spencer.jpg")
            st.subheader("1773:")
            st.markdown("Nasce ***Maria Teresa de Áustria-Este***, rainha da *Sardenha*. (m. 1832)")
            st.image("maria.jpg")
            st.subheader("1778:")
            st.markdown("Nasce ***Gustavo IV Adolfo***, Rei da *Suécia*. (m. 1837)")
            st.image("gustavo.jpg")
            st.subheader("1781:")
            st.markdown("Nasce ***Joseph Karl Stieler***, pintor *alemão*. (m. 1858)")
            st.image("karl.jpg")
            st.subheader("1782:")
            st.markdown("Nasce ***Frederick John Robinson***, 1º Conde de *Ripon*, político *britânico*. (m. 1859)")
            st.image("robinson.jpg")
            st.subheader("1787:")
            st.markdown("Nasce ***Romualdo Antônio de Seixas***, Bispo *brasileiro*. (m. 1860)")
            st.image("seixas.jpeg")
            st.subheader("1797:")
            st.markdown("Nasce ***Maria Doroteia de Württemberg***, arquiduquesa da *Áustria*. (m. 1855)")
            st.image("doroteia.jpg")
            st.markdown("Nasce ***Santos Michelana***, político e diplomata *venezuelano*. (m. 1848)")
            st.image("santos.jpg")
            st.subheader("1819:")
            st.markdown("Nasce ***John Miller Adye***, general *britânico*. (m. 1900)")
            st.image("miller.jpg")
            st.subheader("1831:")
            st.markdown("Nasce ***Harry Atkinson***, político *neozelandês*. (m. 1892)")
            st.image("harry.jpeg")
            st.subheader("1837:")
            st.markdown("Nasce ***Couto de Magalhães***, político, militar e escritor *brasileiro*. (m. 1898)")
            st.image("couto.jpg")
            st.subheader("1838:")
            st.markdown("Nasce ***Khendrup Gyatso***, 11º dalai-lame do *Tibete*. (m. 1856)")
            st.image("gyatso.jpg")
            st.subheader("1847:")
            st.markdown("Nasce ***Emma Albani***, cantora lírica *canadense*. (m. 1930)")
            st.image("emma.jpg")
            st.subheader("1848:")
            st.markdown("Nasce ***Caroline Still Anderson***, médica e ativista *estadunidense*. (m. 1919)")
            st.image("caroline.jpg")
            st.markdown("Nasce ***Jules Bastien-Lepage***, pintor *francês*. (m. 1884)")
            st.image("lepage.jpg")
            st.subheader("1864:")
            st.markdown("Nasce ***Isabel Feodorovna***, Grã-duquesa da *Rússia*. (m. 1918)")
            st.image("isabel.jpg")
            st.subheader("1878:")
            st.markdown("Nasce *** Carlos Saavedra Lamas***, político e escritor *Argentino*. (m. 1959)")
            st.image("lamas.jpg")
            st.subheader("1886:")
            st.markdown("Nasce ***Sakutarō Hagiwara***, poeta *japonês*. (m. 1942)")
            st.image("sakutaro.jpeg")
            st.subheader("1887:")
            st.markdown("Nasce ***Laurence Stephen Lowry***, pintor *inglês*. (m. 1976)")
            st.image("laurence.jpg")
            st.subheader("1889:")
            st.markdown("Nasce ***Philip Noel-Baker***, político, diplomata e atleta *britânico*. (m. 1982)")
            st.image("noel.jpg")
            st.subheader("1896:")
            st.markdown("Nasce ***Edmund Blunden***, poeta *inglês*. (m. 1974)")
            st.image("blunden.jpg")
            st.subheader("1898:")
            st.markdown("Nasce ***Arthur Legat***, piloto de corrida belga. (m. 1960)")
            st.image("legat.jpg")
            st.markdown("Nasce ***Sippi Wallace***, cantora *estadunidense*. (m. 1986)")
            st.image("sippie.png")
            st.subheader("1909:")
            st.markdown("Nasce ***Vicente Feola***, treinador de futebol *brasileiro*. (m. 1975)")
            st.image("feola.jpg")
            st.subheader("1919:")
            st.markdown("Nasce *** Hermann Bondi***, cosmólogo *austro-britânico*. (m. 2005)")
            st.image("bondi.jpg")
            st.subheader("1923:")
            st.markdown("Nasce ***Carlos Páez Vilaró***, empresário e artista plástico *uruguaio*. (m. 2014)")
            st.image("vilaro.jpg")
            st.subheader("1924:")
            st.markdown("Nasce ***Süleyman Demirel***, político *turco*. (m. 2015)")
            st.image("demirel.jpg")
            st.subheader("1931:")
            st.markdown("Nasce ***JShunsuke Kikuchi***, compositor *japonês*. (m. 2021)")
            st.image("kikuchi.jpg")
            st.markdown("Nasce ***Chousuke Ikariya***, ator e comediante *japonês*. (. 2004)")
            st.image("ikariya.jpg")
            st.subheader("1934:")
            st.markdown("Nasce ***Jackson Lago***, médico e político *brasileiro*. (m. 2011)")
            st.image("lago.jpg")
            st.subheader("1937:")
            st.markdown("Nasce ***Tom Waddell***, médico *americano* e fundador dos *Jogos Gays*. (m. 1987)")
            st.image("tom.jpg")
            st.subheader("1939:")
            st.markdown("Nasce ***Bernard Kouchner***, médico e político *francês*.")
            st.image("bernard.jpg")
            st.subheader("1941:")
            st.markdown("Nasce ***Alfio Basile***, treinador *argentino* de futebol.")
            st.image("alfio.jpeg")
            st.subheader("1942:")
            st.markdown("Nasce ***Larry Flynt***, editor *norte-americano*. (m. 2021)")
            st.image("larry.jpg")
            st.subheader("1943:")
            st.markdown("Nasce ***Salvatore Adamo***, cantor *belga*.")
            st.image("Salvatore.jpg")
            st.subheader("1944:")
            st.markdown("Nasce ***Oscar Temaru***, político *polinésio*.")
            st.image("oscar.jpg")
            st.subheader("1945:")
            st.markdown("Nasce ***Gilberto Braga***, dramaturgo *brasileiro*. (m. 2021)")
            st.image("braga.jpeg")
            st.markdown("Nasce ***Celso de Mello***, jurista e magistrado brasileiro.")
            st.image("celso.jpeg")
            st.subheader("1949:")
            st.markdown("Nasce ***Jeannie Berlin***, atriz e roteirista *norte-americana*.")
            st.image("berlin.jpeg")
            st.subheader("1950:")
            st.markdown("Nasce ***Robert Betts Laughlin***, físico *norte-americano*.")
            st.image("robert.jpeg")
            st.subheader("1956:")
            st.markdown("Nasce ***Paulo Gonzo***, cantor *português*.")
            st.image("gonzo.jpg")
            st.subheader("1957:")
            st.markdown("Nasce ***Carlos Paião***, músico *português*.")
            st.image("paiao.jpg")
            st.subheader("1962:")
            st.markdown("Nasce ***Anthony Kiedis***, cantor e compositor *norte-americano*.")
            st.image("kiedis.jpg")
            st.markdown("Nasce ***Magne Furuholmen***, músico *norueguês*.")
            st.image("magne.jpg")
            st.subheader("1963:")
            st.markdown("Nasce ***Mark Hughes***, treinador de futebol *britânico*.")
            st.image("mark.jpeg")
            st.subheader("1966:")
            st.markdown("Nasce ***Ingo Steuer***, patinador artístico *alemão*.")
            st.image("ingo.jpg")
            st.subheader("1967:")
            st.markdown("Nasce ***Miguel Rimba* **, futebolista *boliviano*.")
            st.image("rimba.jpg")
            st.markdown("Nasce ***Tina Arena***, cantora *norte-americana*")
            st.image("tina.jpeg")
            st.subheader("1969:")
            st.markdown("Nasce ***Óscar Ruiz***, árbitro de futebol *colombiano*.")
            st.image("ruiz.jpg")
            st.subheader("1971:")
            st.markdown("Nasce *** Alexei Tikhonov***, patinador artístico *russo*.")
            st.image("alexei.jpg")
            st.subheader("1972:")
            st.markdown("Nasce ***Toni Collette***, atriz *australiana*.")
            st.image("toni.jpg")
            st.markdown("Nasce ***Alessandra Silvestri-Levy***, escritora *brasileira*.")
            st.image("levy.jpg")
            st.markdown("Nasce ***Jenny McCarthy***, atriz *estadunidense*.")
            st.image("jenny.jpg")
            st.subheader("1973:")
            st.markdown("Nasce ***Aishwarya Rai***, atriz *indiana*.")
            st.image("rai.jpg")
            st.subheader("1975:")
            st.markdown("Nasce ***Bo Bice***, cantor norte-americano.")
            st.image("bo.jpg")
            st.subheader("1976:")
            st.markdown("Nasce ***Luís Mário***, futebolista *brasileiro*.")
            st.image("mario.jpg")
            st.subheader("1977:")
            st.markdown("Nasce ***Álvaro***, futebolista *brasileiro*.")
            st.image("alvaro.jpg")
            st.subheader("1978:")
            st.markdown("Nasce ***Lázaro Ramos***, ator *brasileiro*.")
            st.image("ramos.jpeg")
            st.subheader("1981:")
            st.markdown("Nasce ***Thiago Fragoso***, ator *brasileiro*.")
            st.image("thiago.jpg")
            st.markdown("Nasce ***LaTavia Roberson***, cantora, compositora e atriz *norte-americana*.")
            st.image("latavia.jpg")
            st.subheader("1984:")
            st.markdown("Nasce ***Damiano Ferronetti***, futebolista *italiano*.")
            st.image("damiano.jpg")
            st.markdown("Nasce ***Natalia Tena***, atriz *britânica*.")
            st.image("tena.jpeg")
            st.subheader("1986:")
            st.markdown("Nasce ***Penn Badgley***, ator *norte-americano*.")
            st.image("penn.jpg")
            st.subheader("1992:")
            st.markdown("Nasce ***Vladimir Morozov***, patinador artístico *russo*.")
            st.image("vladimir.jpg")
            st.subheader("1993:")
            st.markdown("Nasce ***Pablo Vittar***, cantor e compositor *brasileiro*.")
            st.image("pablo.jpg")
            st.subheader("1996:")
            st.markdown("Nasce ***Yoo Jeong-yeon***, cantora *sul-coreana*.")
            st.image("yoo.jpg")
            st.markdown("Nasce ***Lil Peep***, rapper *norte-americano*.")
            st.image("lil.jpg")
            st.subheader("1999:")
            st.markdown("Nasce ***Buddy Handleson***, ator *norte-americano*.")
            st.image("buddy.jpg")
            st.subheader("2000:")
            st.markdown("Nasce ***Gonzalo Plata***, futebolista *equatoriano*.")
            st.image("plata.jpg")
            st.subheader("2007:")
            st.markdown("Nasce ***Carolina Santos Leão Flores***, estudante *portuguesa*.")
            st.image("carolina.png")
            AcessoAreaSecreta = st.popover("Aceder à Área Secreta")
            with AcessoAreaSecreta:
               animal = st.text_input("Qual é o teu animal de estimação preferido?")
               animal_lower = animal.lower()
            if animal_lower in ["cão", "cadela", "cães", "cadelas" , "cao" , "caes" , "chihuahua" , "chihuahuas"]:
              col1, col2,  col3 = st.columns(3)
              col1.metric("" , "" , "")
              col2.metric("" , 'Parabéns!' , "")
              col3.metric("" , "" , "")
              st.balloons()
              st.balloons()
              st.balloons()
              st.balloons()
        if AteSeculoXIX and condition == True:
            st.subheader("846:")
            st.markdown("Nasce ***Luís II de França***. (m. 879)")
            st.image("luis.jpg")
            st.subheader("1339:")
            st.markdown("Nasce ***Rodolfo IV da Áustria***. (m. 1365)")
            st.image("rodolfo.jpg")
            st.subheader("1526:")
            st.markdown("Nasce ***Catarina Jagelão***, Rainha da *Suécia*. (m. 1583)")
            st.image("jagelão.jpg")
            st.subheader("1530:")
            st.markdown("Nasce ***Étienne de La Boétie***, filósofo e humanista *francês*. (m. 1563)")
            st.image("etienne.jpg")
            st.subheader("1549:")
            st.markdown("Nasce ***Ana de Áustria***, Rainha de *Espanha*. (m. 1580)")
            st.image("ana.jpg")
            st.subheader("1593:")
            st.markdown("Nasce ***Abel Servien***, diplomata *francês*. (m.1659)")
            st.image("abel.jpg")
            st.subheader("1596:")
            st.markdown("Nasce ***Pietro de Cortona***, pintor e arquiteto *toscano*. (m.1669)")
            st.image("pietro.jpeg")
            st.subheader("1636:")
            st.markdown("Nasce ***Nicolas Boileau***, crítico literário e poeta *francês*. (m.1711)")
            st.image("nicolas.jpg")
            st.subheader("1661:")
            st.markdown("Nasce ***Luís, Grande Delfim de França***. (m. 1661)")
            st.image("delfim.jpg")
            st.subheader("1713:")
            st.markdown("Nasce ***Antonio Genovesi***, escritor e filósofo *napolitano*. (m. 1769)")
            st.image("antonio.jpg")
            st.subheader("1717:")
            st.markdown("Nasce ***Ana Teresa de Saboia***, nobre *francesa*. (m.1745)")
            st.image("saboia.jpg")
            st.subheader("1743:")
            st.markdown("Nasce ***Johann Friedrich Wilhelm Herbst***, naturalista e entomologista *alemão*. (m. 1807)")
            st.image("johann.jpg")
            st.subheader("1757:")
            st.markdown("Nasce ***Antonio Canova***, escultor *veneziano*. (m.1822)")
            st.image("canova.jpg")
            st.subheader("1762:")
            st.markdown("Nasce ***Antônio de Santa Úrsula Rodovalho***, religioso franciscano nascido no *Brasil Colonial*. (m. 1817)")
            st.image("franciscanos.jpg" , caption="Grupo de religiosos a envergarem o típico traje franciscano")
            st.markdown("Nasce ***Spencer Perceval***, político *britânico*. (m. 1812)")
            st.image("spencer.jpg")
            st.subheader("1773:")
            st.markdown("Nasce ***Maria Teresa de Áustria-Este***, rainha da *Sardenha*. (m. 1832)")
            st.image("maria.jpg")
            st.subheader("1778:")
            st.markdown("Nasce ***Gustavo IV Adolfo***, Rei da *Suécia*. (m. 1837)")
            st.image("gustavo.jpg")
            st.subheader("1781:")
            st.markdown("Nasce ***Joseph Karl Stieler***, pintor *alemão*. (m. 1858)")
            st.image("karl.jpg")
            st.subheader("1782:")
            st.markdown("Nasce ***Frederick John Robinson***, 1º Conde de *Ripon*, político *britânico*. (m. 1859)")
            st.image("robinson.jpg")
            st.subheader("1787:")
            st.markdown("Nasce ***Romualdo Antônio de Seixas***, Bispo *brasileiro*. (m. 1860)")
            st.image("seixas.jpeg")
            st.subheader("1797:")
            st.markdown("Nasce ***Maria Doroteia de Württemberg***, arquiduquesa da *Áustria*. (m. 1855)")
            st.image("doroteia.jpg")
            st.markdown("Nasce ***Santos Michelana***, político e diplomata *venezuelano*. (m. 1848)")
            st.image("santos.jpg")
        if SeculoXIX and condition == True:
            st.subheader("1819:")
            st.markdown("Nasce ***John Miller Adye***, general *britânico*. (m. 1900)")
            st.image("miller.jpg")
            st.subheader("1831:")
            st.markdown("Nasce ***Harry Atkinson***, político *neozelandês*. (m. 1892)")
            st.image("harry.jpeg")
            st.subheader("1837:")
            st.markdown("Nasce ***Couto de Magalhães***, político, militar e escritor *brasileiro*. (m. 1898)")
            st.image("couto.jpg")
            st.subheader("1838:")
            st.markdown("Nasce ***Khendrup Gyatso***, 11º dalai-lame do *Tibete*. (m. 1856)")
            st.image("gyatso.jpg")
            st.subheader("1847:")
            st.markdown("Nasce ***Emma Albani***, cantora lírica *canadense*. (m. 1930)")
            st.image("emma.jpg")
            st.subheader("1848:")
            st.markdown("Nasce ***Caroline Still Anderson***, médica e ativista *estadunidense*. (m. 1919)")
            st.image("caroline.jpg")
            st.markdown("Nasce ***Jules Bastien-Lepage***, pintor *francês*. (m. 1884)")
            st.image("lepage.jpg")
            st.subheader("1864:")
            st.markdown("Nasce ***Isabel Feodorovna***, Grã-duquesa da *Rússia*. (m. 1918)")
            st.image("isabel.jpg")
            st.subheader("1878:")
            st.markdown("Nasce *** Carlos Saavedra Lamas***, político e escritor *Argentino*. (m. 1959)")
            st.image("lamas.jpg")
            st.subheader("1886:")
            st.markdown("Nasce ***Sakutarō Hagiwara***, poeta *japonês*. (m. 1942)")
            st.image("sakutaro.jpeg")
            st.subheader("1887:")
            st.markdown("Nasce ***Laurence Stephen Lowry***, pintor *inglês*. (m. 1976)")
            st.image("laurence.jpg")
            st.subheader("1889:")
            st.markdown("Nasce ***Philip Noel-Baker***, político, diplomata e atleta *britânico*. (m. 1982)")
            st.image("noel.jpg")
            st.subheader("1896:")
            st.markdown("Nasce ***Edmund Blunden***, poeta *inglês*. (m. 1974)")
            st.image("blunden.jpg")
            st.subheader("1898:")
            st.markdown("Nasce ***Arthur Legat***, piloto de corrida belga. (m. 1960)")
            st.image("legat.jpg")
            st.markdown("Nasce ***Sippi Wallace***, cantora *estadunidense*. (m. 1986)")
            st.image("sippie.png")
        if SeculoXX and condition == True:
            if PrimeiraMetade:
                st.subheader("1909:")
                st.markdown("Nasce ***Vicente Feola***, treinador de futebol *brasileiro*. (m. 1975)")
                st.image("feola.jpg")
                st.subheader("1919:")
                st.markdown("Nasce *** Hermann Bondi***, cosmólogo *austro-britânico*. (m. 2005)")
                st.image("bondi.jpg")
                st.subheader("1923:")
                st.markdown("Nasce ***Carlos Páez Vilaró***, empresário e artista plástico *uruguaio*. (m. 2014)")
                st.image("vilaro.jpg")
                st.subheader("1924:")
                st.markdown("Nasce ***Süleyman Demirel***, político *turco*. (m. 2015)")
                st.image("demirel.jpg")
                st.subheader("1931:")
                st.markdown("Nasce ***JShunsuke Kikuchi***, compositor *japonês*. (m. 2021)")
                st.image("kikuchi.jpg")
                st.markdown("Nasce ***Chousuke Ikariya***, ator e comediante *japonês*. (. 2004)")
                st.image("ikariya.jpg")
                st.subheader("1934:")
                st.markdown("Nasce ***Jackson Lago***, médico e político *brasileiro*. (m. 2011)")
                st.image("lago.jpg")
                st.subheader("1937:")
                st.markdown("Nasce ***Tom Waddell***, médico *americano* e fundador dos *Jogos Gays*. (m. 1987)")
                st.image("tom.jpg")
                st.subheader("1939:")
                st.markdown("Nasce ***Bernard Kouchner***, médico e político *francês*.")
                st.image("bernard.jpg")
                st.subheader("1941:")
                st.markdown("Nasce ***Alfio Basile***, treinador *argentino* de futebol.")
                st.image("alfio.jpeg")
                st.subheader("1942:")
                st.markdown("Nasce ***Larry Flynt***, editor *norte-americano*. (m. 2021)")
                st.image("larry.jpg")
                st.subheader("1943:")
                st.markdown("Nasce ***Salvatore Adamo***, cantor *belga*.")
                st.image("Salvatore.jpg")
                st.subheader("1944:")
                st.markdown("Nasce ***Oscar Temaru***, político *polinésio*.")
                st.image("oscar.jpg")
                st.subheader("1945:")
                st.markdown("Nasce ***Gilberto Braga***, dramaturgo *brasileiro*. (m. 2021)")
                st.image("braga.jpeg")
                st.markdown("Nasce ***Celso de Mello***, jurista e magistrado brasileiro.")
                st.image("celso.jpeg")
                st.subheader("1949:")
                st.markdown("Nasce ***Jeannie Berlin***, atriz e roteirista *norte-americana*.")
                st.image("berlin.jpeg")
                st.subheader("1950:")
                st.markdown("Nasce ***Robert Betts Laughlin***, físico *norte-americano*.")
                st.image("robert.jpeg")
            if SegundaMetade:
                st.subheader("1956:")
                st.markdown("Nasce ***Paulo Gonzo***, cantor *português*.")
                st.image("gonzo.jpg")
                st.subheader("1957:")
                st.markdown("Nasce ***Carlos Paião***, músico *português*.")
                st.image("paiao.jpg")
                st.subheader("1962:")
                st.markdown("Nasce ***Anthony Kiedis***, cantor e compositor *norte-americano*.")
                st.image("kiedis.jpg")
                st.markdown("Nasce ***Magne Furuholmen***, músico *norueguês*.")
                st.image("magne.jpg")
                st.subheader("1963:")
                st.markdown("Nasce ***Mark Hughes***, treinador de futebol *britânico*.")
                st.image("mark.jpeg")
                st.subheader("1966:")
                st.markdown("Nasce ***Ingo Steuer***, patinador artístico *alemão*.")
                st.image("ingo.jpg")
                st.subheader("1967:")
                st.markdown("Nasce ***Miguel Rimba* **, futebolista *boliviano*.")
                st.image("rimba.jpg")
                st.markdown("Nasce ***Tina Arena***, cantora *norte-americana*")
                st.image("tina.jpeg")
                st.subheader("1969:")
                st.markdown("Nasce ***Óscar Ruiz***, árbitro de futebol *colombiano*.")
                st.image("ruiz.jpg")
                st.subheader("1971:")
                st.markdown("Nasce *** Alexei Tikhonov***, patinador artístico *russo*.")
                st.image("alexei.jpg")
                st.subheader("1972:")
                st.markdown("Nasce ***Toni Collette***, atriz *australiana*.")
                st.image("toni.jpg")
                st.markdown("Nasce ***Alessandra Silvestri-Levy***, escritora *brasileira*.")
                st.image("levy.jpg")
                st.markdown("Nasce ***Jenny McCarthy***, atriz *estadunidense*.")
                st.image("jenny.jpg")
                st.subheader("1973:")
                st.markdown("Nasce ***Aishwarya Rai***, atriz *indiana*.")
                st.image("rai.jpg")
                st.subheader("1975:")
                st.markdown("Nasce ***Bo Bice***, cantor norte-americano.")
                st.image("bo.jpg")
                st.subheader("1976:")
                st.markdown("Nasce ***Luís Mário***, futebolista *brasileiro*.")
                st.image("mario.jpg")
                st.subheader("1977:")
                st.markdown("Nasce ***Álvaro***, futebolista *brasileiro*.")
                st.image("alvaro.jpg")
                st.subheader("1978:")
                st.markdown("Nasce ***Lázaro Ramos***, ator *brasileiro*.")
                st.image("ramos.jpeg")
                st.subheader("1981:")
                st.markdown("Nasce ***Thiago Fragoso***, ator *brasileiro*.")
                st.image("thiago.jpg")
                st.markdown("Nasce ***LaTavia Roberson***, cantora, compositora e atriz *norte-americana*.")
                st.image("latavia.jpg")
                st.subheader("1984:")
                st.markdown("Nasce ***Damiano Ferronetti***, futebolista *italiano*.")
                st.image("damiano.jpg")
                st.markdown("Nasce ***Natalia Tena***, atriz *britânica*.")
                st.image("tena.jpeg")
                st.subheader("1986:")
                st.markdown("Nasce ***Penn Badgley***, ator *norte-americano*.")
                st.image("penn.jpg")
                st.subheader("1992:")
                st.markdown("Nasce ***Vladimir Morozov***, patinador artístico *russo*.")
                st.image("vladimir.jpg")
                st.subheader("1993:")
                st.markdown("Nasce ***Pablo Vittar***, cantor e compositor *brasileiro*.")
                st.image("pablo.jpg")
                st.subheader("1996:")
                st.markdown("Nasce ***Yoo Jeong-yeon***, cantora *sul-coreana*.")
                st.image("yoo.jpg")
                st.markdown("Nasce ***Lil Peep***, rapper *norte-americano*.")
                st.image("lil.jpg")
                st.subheader("1999:")
                st.markdown("Nasce ***Buddy Handleson***, ator *norte-americano*.")
                st.image("buddy.jpg")
                st.subheader("2000:")
                st.markdown("Nasce ***Gonzalo Plata***, futebolista *equatoriano*.")
                st.image("plata.jpg")
        if SeculoXXI and condition == True:
            st.subheader("2007:")
            st.markdown("Nasce ***Carolina Santos Leão Flores***, estudante *portuguesa*.")
            st.image("carolina.png")
            AcessoAreaSecreta = st.popover("Aceder à Área Secreta")
            with AcessoAreaSecreta:
               animal = st.text_input("Qual é o teu animal de estimação preferido?")
               animal_lower = animal.lower()
            if animal_lower in ["cão", "cadela", "cães", "cadelas" , "cao" , "caes" , "chihuahua" , "chihuahuas"]:
              col1, col2,  col3 = st.columns(3)
              col1.metric("" , "" , "")
              col2.metric("" , 'Parabéns!' , "")
              col3.metric("" , "" , "")
              st.balloons()
              st.balloons()
              st.balloons()
              st.balloons()

#Mortes:
elif Mortes:
        st.subheader("Principais Mortes" , divider= "rainbow")
        #Estabelecer que épocas evidenciar:
        with st.sidebar:
            st.markdown("**Por favor, selecione as principais épocas a visualizar:**")
            AteSeculoXIX = st.toggle("Anteriores ao século XIX")
            SeculoXIX = st.toggle("Século XIX")
            SeculoXX = st.toggle("Século XX")
            SeculoXXI = st.toggle("Século XXI")
            TodasAsEpocas = st.toggle("Todas as épocas")
        if TodasAsEpocas:
            condition = False
            st.subheader("955:")
            st.markdown("Morre ***Henrique I***, duque da *Baviera*. (n. 919)")
            st.image("henrique.jpg")
            st.subheader("1155:")
            st.markdown("Morre ***Fernão Peres de Trava***, nobre *galego*. (n. 1100)")
            st.image("peres.png")
            st.subheader("1391:")
            st.markdown("Morre ***Amadeu VII***, conde de *Saboia*. (n. 1360)")
            st.image("amadeu.jpg")
            st.subheader("1399:")
            st.markdown("Morre ***João V***, duque da *Bretanha*. (n. 1339)")
            st.image("joao.jpg")
            st.subheader("1406:")
            st.markdown("Morre ***Joana de Brabante***, duquesa de *Brabante*. (n. 1322)")
            st.image("joana.jpg")
            st.subheader("1431:")
            st.markdown("Morre ***D. Nuno Álvares Pereira***, beato e contestável *português*. (n. 1360)")
            st.image("nuno.jpg")
            st.subheader("1457:")
            st.markdown("Morre ***Francesco Foscari***, doge de *Veneza*. (n. 1373)")
            st.image("francesco.jpg")
            st.subheader("1463:")
            st.markdown("Morre ***David***, Imperador de *Trebizonda*. (n. 1408)")
            st.image("david.jpg")
            st.subheader("1546:")
            st.markdown("Morre ***Giulio Romano***, pintor e arquiteto *italiano*. (n. 1499)")
            st.image("giulio.jpg")
            st.subheader("1700:")
            st.markdown("Morre ***Carlo II de Espanha***. (n. 1661)")
            st.image("carlosii.jpg")
            st.subheader("1730:")
            st.markdown("Morre ***Luigi Ferdinando Marsigli***, botânico, geógrafo e naturalista *italiano* (n. 1658)")
            st.image("luigi.png")
            st.subheader("1776:")
            st.markdown("Morre ***Francisco de Saldanha da Gama***, cardeal *português*. (n. 1723)")
            st.image("saldanha.jpg")
            st.subheader("1860:")
            st.markdown("Morre ***Carlota da Prússia***. (n. 1798)")
            st.image("carlota.jpg")
            st.subheader("1877:")
            st.markdown("Morre ***Oliver P. Morton***, político *norte-americano*. (n. 1823)")
            st.image("oliver.jpg")
            st.subheader("1894:")
            st.markdown("Morre ***Alexandre III da Rússia***. (n. 1845)")
            st.image("alexandre.jpg")
            st.subheader("1899:")
            st.markdown("Morre ***Alexandre Brodowski***, engenheiro *polonês*. (n. 1856)")
            st.image("alksander.jpg")
            st.subheader("1922:")
            st.markdown("Morre ***Lima Barreto***, escritor *brasileiro*. (n. 1881)")
            st.image("lima.png")
            st.subheader("1952:")
            st.markdown('Morre ***Januário Cicco***, médico *brasileiro*. (n. 1881)')
            st.image("cicco.jpeg")
            st.subheader("1956:")
            st.markdown("Morre ***Pietro Badoglio***, militar e político *italiano*. (n. 1871)")
            st.image("pietro.jpg")
            st.subheader("1968:")
            st.markdown("Morre ***Francisco Campos***, jurista e político *brasileiro*. (n. 1891)")
            st.image("campos.jpg")
            st.markdown("Morre ***Ludowika Jakobsson***, patinadora artística *teuto-finlandesa*. (n. 1884)")
            st.image("lodowika.jpg")
            st.subheader("1972:")
            st.markdown("Morre ***Ezra Pound***, poeta *estadunidense*. (n. 1885)")
            st.image("ezra.jpg")
            st.subheader("1987:")
            st.markdown("Morre ***René Lévesque***, estadista *canadense*. (n. 1922)")
            st.image("rene.jpg")
            st.subheader("1993:")
            st.markdown("Morre ***Felipe Pinheiro***, ator e redator *brasileiro*. (n. 1960)")
            st.image("pinheiro.jpeg")
            st.subheader("2007:")
            st.markdown("Morre ***Paul Tibbets***, piloto militar *norte-americano*. (n. 1915)")
            st.image("paul.jpg")
            st.subheader("2008:")
            st.markdown("Morre ***Yma Sumac***, cantora *peruana*. (n. 1922)")
            st.image("yma.jpeg")
            st.subheader("2009:")
            st.markdown("Morre ***Alda Merini***, escritora e poetisa *italiana*. (n. 1931)")
            st.image("alda.jpg")
            st.subheader("2015:")
            st.markdown("Morre ***Günter Schabowski***, político *alemão*. (n. 1929)")
            st.image("gunter.jpg")
            st.markdown("Morre ***Fred Thompson***, político e ator *norte-americano*. (n. 1942)")
            st.image("fred.jpg")
            st.markdown("Morre ***José Fonseca e Costa***, cineasta *português*. (n. 1933)")
            st.image("costa.png")
            st.subheader("2019:")
            st.markdown("Morre ***Ary Kara***, advogado e político *brasileiro*. (n. 1942)")
            st.image("ary.jpg")
            st.subheader("2022:")
            st.markdown("Morre ***Takeoff***, rapper *estadunidense*. (n. 1994)")
            st.image("takeoff.jpg")
            st.subheader("2023:")
            st.markdown("Morre ***Peter White***, ator *norte-americano*. (n. 1937)")
            st.image("peter.jpeg")
            st.subheader("2024:")
            st.markdown("Morre ***João Scognamiglio Clá Dias***, pesbítero católico *brasileiro*. (n. 1939)")
            st.image("dias.jpg")
        if AteSeculoXIX and condition == True:
            st.subheader("955:")
            st.markdown("Morre ***Henrique I***, duque da *Baviera*. (n. 919)")
            st.image("henrique.jpg")
            st.subheader("1155:")
            st.markdown("Morre ***Fernão Peres de Trava***, nobre *galego*. (n. 1100)")
            st.image("peres.png")
            st.subheader("1391:")
            st.markdown("Morre ***Amadeu VII***, conde de *Saboia*. (n. 1360)")
            st.image("amadeu.jpg")
            st.subheader("1399:")
            st.markdown("Morre ***João V***, duque da *Bretanha*. (n. 1339)")
            st.image("joao.jpg")
            st.subheader("1406:")
            st.markdown("Morre ***Joana de Brabante***, duquesa de *Brabante*. (n. 1322)")
            st.image("joana.jpg")
            st.subheader("1431:")
            st.markdown("Morre ***D. Nuno Álvares Pereira***, beato e contestável *português*. (n. 1360)")
            st.image("nuno.jpg")
            st.subheader("1457:")
            st.markdown("Morre ***Francesco Foscari***, doge de *Veneza*. (n. 1373)")
            st.image("francesco.jpg")
            st.subheader("1463:")
            st.markdown("Morre ***David***, Imperador de *Trebizonda*. (n. 1408)")
            st.image("david.jpg")
            st.subheader("1546:")
            st.markdown("Morre ***Giulio Romano***, pintor e arquiteto *italiano*. (n. 1499)")
            st.image("giulio.jpg")
            st.subheader("1700:")
            st.markdown("Morre ***Carlo II de Espanha***. (n. 1661)")
            st.image("carlosii.jpg")
            st.subheader("1730:")
            st.markdown("Morre ***Luigi Ferdinando Marsigli***, botânico, geógrafo e naturalista *italiano* (n. 1658)")
            st.image("luigi.png")
            st.subheader("1776:")
            st.markdown("Morre ***Francisco de Saldanha da Gama***, cardeal *português*. (n. 1723)")
            st.image("saldanha.jpg")
        if SeculoXIX and condition == True:
            st.subheader("1860:")
            st.markdown("Morre ***Carlota da Prússia***. (n. 1798)")
            st.image("carlota.jpg")
            st.subheader("1877:")
            st.markdown("Morre ***Oliver P. Morton***, político *norte-americano*. (n. 1823)")
            st.image("oliver.jpg")
            st.subheader("1894:")
            st.markdown("Morre ***Alexandre III da Rússia***. (n. 1845)")
            st.image("alexandre.jpg")
            st.subheader("1899:")
            st.markdown("Morre ***Alexandre Brodowski***, engenheiro *polonês*. (n. 1856)")
        if SeculoXX and condition == True:
            st.subheader("1922:")
            st.markdown("Morre ***Lima Barreto***, escritor *brasileiro*. (n. 1881)")
            st.image("lima.png")
            st.subheader("1952:")
            st.markdown('Morre ***Januário Cicco***, médico *brasileiro*. (n. 1881)')
            st.image("cicco.jpeg")
            st.subheader("1956:")
            st.markdown("Morre ***Pietro Badoglio***, militar e político *italiano*. (n. 1871)")
            st.image("pietro.jpg")
            st.subheader("1968:")
            st.markdown("Morre ***Francisco Campos***, jurista e político *brasileiro*. (n. 1891)")
            st.image("campos.jpg")
            st.markdown("Morre ***Ludowika Jakobsson***, patinadora artística *teuto-finlandesa*. (n. 1884)")
            st.image("lodowika.jpg")
            st.subheader("1972:")
            st.markdown("Morre ***Ezra Pound***, poeta *estadunidense*. (n. 1885)")
            st.image("ezra.jpg")
            st.subheader("1987:")
            st.markdown("Morre ***René Lévesque***, estadista *canadense*. (n. 1922)")
            st.image("rene.jpg")
            st.subheader("1993:")
            st.markdown("Morre ***Felipe Pinheiro***, ator e redator *brasileiro*. (n. 1960)")
            st.image("pinheiro.jpeg")
        if SeculoXXI and condition == True:
            st.subheader("2007:")
            st.markdown("Morre ***Paul Tibbets***, piloto militar *norte-americano*. (n. 1915)")
            st.image("paul.jpg")
            st.subheader("2008:")
            st.markdown("Morre ***Yma Sumac***, cantora *peruana*. (n. 1922)")
            st.image("yma.jpeg")
            st.subheader("2009:")
            st.markdown("Morre ***Alda Merini***, escritora e poetisa *italiana*. (n. 1931)")
            st.image("alda.jpg")
            st.subheader("2015:")
            st.markdown("Morre ***Günter Schabowski***, político *alemão*. (n. 1929)")
            st.image("gunter.jpg")
            st.markdown("Morre ***Fred Thompson***, político e ator *norte-americano*. (n. 1942)")
            st.image("fred.jpg")
            st.markdown("Morre ***José Fonseca e Costa***, cineasta *português*. (n. 1933)")
            st.image("costa.png")
            st.subheader("2019:")
            st.markdown("Morre ***Ary Kara***, advogado e político *brasileiro*. (n. 1942)")
            st.image("ary.jpg")
            st.subheader("2022:")
            st.markdown("Morre ***Takeoff***, rapper *estadunidense*. (n. 1994)")
            st.image("takeoff.jpg")
            st.subheader("2023:")
            st.markdown("Morre ***Peter White***, ator *norte-americano*. (n. 1937)")
            st.image("peter.jpeg")
            st.subheader("2024:")
            st.markdown("Morre ***João Scognamiglio Clá Dias***, pesbítero católico *brasileiro*. (n. 1939)")
            st.image("dias.jpg")